sudo: false
language: cpp

compiler:
  - clang
  - g++
install:
  - if [ "$CXX" = "g++" ] && [ "$CXX_FLAGS" = "-std=c++11" ]; then export CXX="g++-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - liblua5.2-dev
    - libluajit-5.1-dev
    - libboost-all-dev
    - g++-4.8
    - llvm-gcc-4.6
    - cmake
env:
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03 LUALIB=lua5.2 KAGUYA_NO_USERDATA_TYPE_CHECK=0
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11 LUALIB=lua5.2 KAGUYA_NO_USERDATA_TYPE_CHECK=0
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03 LUALIB=luajit KAGUYA_NO_USERDATA_TYPE_CHECK=0
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11 LUALIB=luajit KAGUYA_NO_USERDATA_TYPE_CHECK=0
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03 LUALIB=lua5.2 KAGUYA_NO_USERDATA_TYPE_CHECK=1
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11 LUALIB=lua5.2 KAGUYA_NO_USERDATA_TYPE_CHECK=1
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03 LUALIB=luajit KAGUYA_NO_USERDATA_TYPE_CHECK=1
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11 LUALIB=luajit KAGUYA_NO_USERDATA_TYPE_CHECK=1
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DLUA_SEARCH_LIB_NAME=${LUALIB} -DKAGUYA_NO_USERDATA_TYPE_CHECK=${KAGUYA_NO_USERDATA_TYPE_CHECK} && make && CTEST_OUTPUT_ON_FAILURE=1 make test
after_success:
  - export GCOV="gcov-4.8";
  - export CXX="g++-4.8";
  - rm -Rf ./*
  - cmake ../ -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DLUA_SEARCH_LIB_NAME=${LUALIB}
  - make
  - ctest
  - bash <(curl -s https://codecov.io/bash) -p . -x "$GCOV"
